#!/bin/sh
#
# motd	Prepares /etc/motd file
#
# chkconfig: 2345 99 05
# description: Prepares /etc/motd file
#
### BEGIN INIT INFO
# Provides: motd
# Default-Start: 2345
# Default-Stop: 0 1 6
# Short-Description: Prepares /etc/motd file
# Description: Prepares /etc/motd file
### END INIT INFO

HOSTNAME=`/bin/uname -a | awk '{print $2}'`
IP_ADDRESS=`ip addr list |grep eth | grep "inet " | cut -d' ' -f6 | cut -d/ -f1`

clear
echo -e "\nAbiquo Server\n\nHostname: $HOSTNAME" > /etc/motd
cat /etc/abiquo-release >> /etc/motd

echo -e "\nThe Abiquo server is now running. You can login from a Web browser at:" >> /etc/motd

for ip in $IP_ADDRESS; do
	echo -e "http://$ip" >> /etc/motd
done
echo >> /etc/motd

exit 0
